All-operators
geo-engine/docs pull request #21
Opened 2022-06-09 14:06 UTC by ChristianBeilschmidt

2022-06-10 10:00 UTC, michaelmattig requested changes

2022-06-10 15:11 UTC, ChristianBeilschmidt commented on src/operators/visualpointclustering.md
> +| `minRadiusPx`      | number                                                                                  | Minimum circle radius in screen pixels                                       | <pre>10
number is not necessarily an integer, could be float instead

2022-06-10 15:22 UTC, ChristianBeilschmidt commented on src/plots/histogram.md
> +| `buckets`     | (Optional) number                                       | The number of buckets.                                                                                | `20`
[2f39715](https://github.com/geo-engine/docs/pull/21/commits/2f39715d7e10665ed08e7788d7033c159d9e2e99)

2022-06-10 15:22 UTC, ChristianBeilschmidt commented on src/plots/histogram.md
> +If `bounds` or `buckets` are unset, the operator needs to process the data twice to compute these values.
[2f39715](https://github.com/geo-engine/docs/pull/21/commits/2f39715d7e10665ed08e7788d7033c159d9e2e99)

2022-06-10 15:22 UTC, ChristianBeilschmidt commented on src/plots/histogram.md
> +| `bounds`      | `HistogramBounds` (either `Data` or specified `Values`) | If `Data`, it computes the bounds of the underlying data. If `Values`, one can specify custom bounds. | <pre><code>{<br>&nb
[2f39715](https://github.com/geo-engine/docs/pull/21/commits/2f39715d7e10665ed08e7788d7033c159d9e2e99)

2022-06-10 15:22 UTC, ChristianBeilschmidt commented on src/plots/histogram.md
> +Then, you can use a histogram with a suitable number of buckets to visualize and assess this.
[2f39715](https://github.com/geo-engine/docs/pull/21/commits/2f39715d7e10665ed08e7788d7033c159d9e2e99)

2022-06-10 15:22 UTC, ChristianBeilschmidt commented on src/plots/histogram.md
> +The output is a plot in Vega-Lite specification.
[2f39715](https://github.com/geo-engine/docs/pull/21/commits/2f39715d7e10665ed08e7788d7033c159d9e2e99)

2022-06-10 15:22 UTC, ChristianBeilschmidt commented on src/operators/visualpointclustering.md
> +| `minRadiusPx`      | number                                                                                  | Minimum circle radius in screen pixels                                       | <pre>10
[92741ea](https://github.com/geo-engine/docs/pull/21/commits/92741ea03e0115bed4f137a082c887e7cba67250)

2022-06-10 15:23 UTC, ChristianBeilschmidt commented on src/operators/timeshift.md
> +| `value`       | integer                                     | the size of the step               | <pre>-1</pre>       |
[e61fc8b](https://github.com/geo-engine/docs/pull/21/commits/e61fc8b1504e131ddba770f6fe22e74408bfe4ee)

2022-06-10 15:23 UTC, ChristianBeilschmidt commented on src/operators/timeshift.md
> +It shifts the query rectangle by a given amount of time and modifies the result data accordingly.
[e61fc8b](https://github.com/geo-engine/docs/pull/21/commits/e61fc8b1504e131ddba770f6fe22e74408bfe4ee)

2022-06-10 15:23 UTC, ChristianBeilschmidt commented on src/operators/timeshift.md
> +Then, you can use both workflows as sources of an `Expression` operator.
[e61fc8b](https://github.com/geo-engine/docs/pull/21/commits/e61fc8b1504e131ddba770f6fe22e74408bfe4ee)

2022-06-10 15:28 UTC, ChristianBeilschmidt commented on src/plots/featureattributevaluesoverTtime.md
> +Then, you can use a multi-line plot to visualize the trees by their id.
[3ec2243](https://github.com/geo-engine/docs/pull/21/commits/3ec22433f7b24284afd337bd2a3dca7af073a360)

2022-06-10 16:01 UTC, michaelmattig commented on src/operators/visualpointclustering.md
> +| `minRadiusPx`      | number                                                                                  | Minimum circle radius in screen pixels                                       | <pre>10
so you support floating point for the radius?

2022-06-10 16:04 UTC, michaelmattig commented on src/plots/histogram.md
> +| `buckets`     | (Optional) number                                       | The number of buckets.                                                                                | `20`
for the buckets: shouldn't you say how it is calculated? also it's more like guessed.

2022-06-13 08:13 UTC, ChristianBeilschmidt commented on src/operators/visualpointclustering.md
> +| `minRadiusPx`      | number                                                                                  | Minimum circle radius in screen pixels                                       | <pre>10
Yes, for instance, if you have a radius of 2.5px, your circle has a diameter of 5px. So it is not unreasonable, because you could not express that.

2022-06-13 08:14 UTC, ChristianBeilschmidt commented on src/plots/histogram.md
> +| `buckets`     | (Optional) number                                       | The number of buckets.                                                                                | `20`
This is described under the notes section.

2022-06-13 09:16 UTC, michaelmattig commented
bors merge

2022-06-13 09:16 UTC, merged