workflow api
geo-engine/docs pull request #22
Opened 2022-06-09 15:41 UTC by michaelmattig

2022-06-09 15:42 UTC, michaelmattig commented
![](https://github.trello.services/images/mini-trello-icon.png) [Result Descriptor mit Bounds](https://trello.com/c/yVpxHCmP/259-result-descriptor-mit-bounds)

2022-06-09 16:04 UTC, ChristianBeilschmidt requested changes

2022-06-09 16:04 UTC, ChristianBeilschmidt commented on src/api/workflows.md
> +  "columns": {},
maybe add one or two columns

2022-06-13 10:19 UTC, michaelmattig commented on src/api/workflows.md
> +  "columns": {},
79d799cc77cea900df4177afaa19dd683d8ca211

2022-06-13 13:01 UTC, ChristianBeilschmidt approved these changes

2022-06-17 11:30 UTC, merged